"""empty message

Revision ID: a0701c86ac6c
Revises: 
Create Date: 2022-04-26 13:28:54.564635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0701c86ac6c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aquarium',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('volume_in_liter', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aquarium', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aquarium_name'), ['name'], unique=True)

    op.create_table('chemical',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('fertilizer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('aquarium_temperature',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquarium.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aquarium_temperature', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aquarium_temperature_timestamp'), ['timestamp'], unique=False)

    op.create_table('fertilization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('amount_in_milliliter', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('aquarium_id', sa.Integer(), nullable=False),
    sa.Column('fertilizer_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aquarium_id'], ['aquarium.id'], ),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fertilizer_ingredients',
    sa.Column('fertilizer_id', sa.Integer(), nullable=False),
    sa.Column('chemical_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['chemical_id'], ['chemical.id'], ),
    sa.ForeignKeyConstraint(['fertilizer_id'], ['fertilizer.id'], ),
    sa.PrimaryKeyConstraint('fertilizer_id', 'chemical_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fertilizer_ingredients')
    op.drop_table('fertilization')
    with op.batch_alter_table('aquarium_temperature', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aquarium_temperature_timestamp'))

    op.drop_table('aquarium_temperature')
    op.drop_table('fertilizer')
    op.drop_table('chemical')
    with op.batch_alter_table('aquarium', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aquarium_name'))

    op.drop_table('aquarium')
    # ### end Alembic commands ###
